#!/bin/bash

## -----------------------------------------------------------------------------
# prepare report
# *.pre -> *.email
#
[[ ! -f flow.lib ]] || [[ ! -f flow.cfg ]] && echo "Error: configure file isn't find or invalid startup directory." && exit

. flow.cfg
. flow.lib

[ `ls $LOG/*.ski 2>/dev/null | wc -l` -eq 0 ] || ls $LOG/*.ski | while read b; do \
    echo $b | sed -e 's/\.[^.]*$//' | while read a; do \
        rm -f $a.{ski,log}
    done
    rm -f $b
done

[ `ls $LOG/*.pre 2>/dev/null | wc -l` -eq 0 ] || ls $LOG/*.pre | while read b; do \
    echo $b | sed -e 's/\.[^.]*$//' | while read a; do \
        mv $a.{pre,log} $TMP
        #echo $TMP/$(basename $a)
        echo $a
    done | grep -o '[^/]*$' | awk -v PERIOD="$PERIOD" '{
        if(PERIOD == "daily"){
            print substr($0,0,10);
        }
        else if(PERIOD == "hourly"){
            print substr($0,0,13);
        }
        else if(PERIOD == "minutely"){
            print substr($0,0,16);
        }
    }'
done | sort | uniq | while read a; do \
    mkdir -p $EMAIL/$a
    mv $TMP/$a*.{pre,log} $EMAIL/$a
    #echo $a
done

# --- --- --- --- --- --- ---
PWD=`pwd`; cd $EMAIL
find * -maxdepth 0 -type d 2>/dev/null | sed 's|.*/||' | while read b; do \
    cat $b/*.pre >> $b.body
    tar -cjf $b.tar.bz2 $b > /dev/null 2>&1

    report $b && (
            echo "$REPORT $b success"
            bzip2 -z $b.body
            mv $b.{body.bz2,tar.bz2} $BACKUP
            rm -dr $b
            rm -f $b.{body,tar.bz2}
    ) || (
            echo "$REPORT $b error"
    )

#    if [ "$REPORT" == "ftp" ]; then
#        ftp $b && (
#            echo "ftp $b ok"
#            bzip2 -z $b.body
#            mv $b.{body.bz2,tar.bz2} $BACKUP
#            rm -dr $b
#            rm -f $b.{body,tar.bz2}
#        ) || (
#            echo "ftp $b error"
#        )
#    fi

#    if [ "$REPORT" == "email" ]; then
#        email $b && (
#            echo "email $b ok"
#            bzip2 -z $b.body
#            mv $b.{body.bz2,tar.bz2} $BACKUP
#            rm -dr $b
#            rm -f $b.{body,tar.bz2}
#        ) || (
#            echo "email $b error"
#        )
#    fi

#    cat $b.body | mutt -s "$SUBJ // $b" $EMAIL -a $b.tar.bz2 && (
#        bzip2 -z $b.body
#        mv $b.{body.bz2,tar.bz2} $BACKUP
#        rm -dr $b
#        echo 'email: '$b' - ok'
#    )

done
cd $PWD

# --- --- --- --- --- --- ---
